### ISSUE TITLE
uninstall.php is not used

### ISSUE THREAD

**Issue by perifer** [Svanmark/Wordpress-Plugin-Boilerplate#1]
From what I can see, unistall.php is not called anywhere. I did this in myplugin.php:

``` php
$MyPlugin = new MyPlugin\App();

register_activation_hook(__FILE__, array($MyPlugin, 'install'));
register_deactivation_hook(__FILE__, array($MyPlugin, 'uninstall'));
```

**Comment by Svanmark** [comment]
According to WordPress documentation uninstall.php is a "magic" file which will automatically run on these conditions: "A plugin is considered uninstalled if a user has deactivated the plugin, and then clicks the delete link within the WordPress Admin."

Please refer to the documentation here if you need more information: https://developer.wordpress.org/plugins/the-basics/uninstall-methods/#method-2-uninstall-php

**Comment by Svanmark** [comment]
However, for a better streamlined approach we could switch over to include both a deactivation and activation hook. 

Or maybe, since the uninstall.php is empty, just delete it and let the developer register uninstall hooks as preferred.

**Comment by perifer** [comment]
Thanks! That documentation really speaks to me: "Less experienced developers sometimes make the mistake of using the deactivation hook for this purpose"
